
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 24 21:42:40 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 9;
  public static final int ASSIGNMENT = 12;
  public static final int NOT_EQUAL = 26;
  public static final int CONTINUE = 46;
  public static final int GREATER = 27;
  public static final int SEMI = 10;
  public static final int LESS = 30;
  public static final int MINUS = 19;
  public static final int RCBRACKET = 8;
  public static final int AND = 42;
  public static final int OR = 47;
  public static final int COMMA = 11;
  public static final int INC = 17;
  public static final int DIV = 33;
  public static final int LESS_EQUAL = 29;
  public static final int PLUS = 31;
  public static final int IF = 40;
  public static final int RRBRACKET = 16;
  public static final int FINDANY = 36;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int EQUAL = 25;
  public static final int GREATER_EQUAL = 28;
  public static final int RSBRACKET = 14;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int NUMBER = 4;
  public static final int MOD = 34;
  public static final int BREAK = 43;
  public static final int IDENT = 5;
  public static final int VOID = 21;
  public static final int ARROW = 41;
  public static final int FOREACH = 48;
  public static final int COLON = 38;
  public static final int ELSE = 20;
  public static final int LCBRACKET = 7;
  public static final int POINT = 45;
  public static final int READ = 22;
  public static final int WHILE = 44;
  public static final int CHARCONST = 2;
  public static final int EXTENDS = 39;
  public static final int BOOLCONST = 3;
  public static final int PROG = 6;
  public static final int LRBRACKET = 15;
  public static final int DEC = 18;
  public static final int PRINT = 23;
  public static final int LSBRACKET = 13;
  public static final int FINDANDREPLACE = 37;
}

